name: Validate and Deploy XGBoost Model

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    name: Validate and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run validation script
    - name: Validate model
      run: python model_validation.py

    # Log in to GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Configure Google Cloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/housing-prediction

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy housing-prediction \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/housing-prediction \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
